a = input('Digite algo ')
print('O tipo primitivo deste valor é', type(a))
print('Só tem espaços? ', a.isspace())
print('Só tem número? ', a.isnumeric())
print('É alfabético? ', a.isalpha())
print('É alfanumérico? ', a.isalnum())
print('Está em maiusculas? ', a.isupper())
print('Está em minuscula? ', a.islower())
print('Está capitalizado? ', a.istitle())